### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by wutong4012** [rosewang2008/language_modeling_via_stochastic_processes#1]
https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/693a37490ec8761fc20798e4083528eca4dc4303/language_modeling_via_stochastic_processes/scripts/train_encoder.py#L76-L77

Thank you very much for open-sourcing your work.

For these two lines, when I run it, I find that the attribute _**A**_ of the _dataset_ cannot be found, and the corresponding _data_params.**dt**_ cannot be found in the **brownian_bridge.yaml** file.

I don't know if my operation is wrong, I look forward to your answer.

**Comment by rosewang2008** [comment]
Ah, that's old code that shouldn't be there. I've now removed that function. Thanks for bringing this to my attention!
