### ISSUE TITLE
Issues during encoder training with wikisection data

### ISSUE THREAD

**Issue by zcsheng95** [rosewang2008/language_modeling_via_stochastic_processes#14]
Hi Rose,

The issue occurred during the testing phase. The error message reads like:

`ValueError: 'self.log(test_loss, [3.5329943])' was called, but 'ndarray' values cannot be logged`

And it was raised from pytorch_lighting/core/lighting.py

Do you have any ideas?

Thanks so much!

Zhecheng

**Comment by rosewang2008** [comment]
Hey! Thanks for raising this to my attention. It seems like the current version logs a single-element _list_ when it should just log the element. 

FWIW, the current repository contains a lot of refactoring bugs which I've been diligently working through. I expect to release a cleaner, reproducible version in due time. Apologies for the wait!

**Comment by zcsheng95** [comment]
Thanks Rose. Another one quick question: Is it feasible to get the parameters that characterizes the learned latent space from the current code?

**Comment by rosewang2008** [comment]
If you mean training the encoder, then technically yes---however there are a lot of bugs that I introduced in refactoring, eg if-conditions being incorrect mentioned here: https://github.com/rosewang2008/language_modeling_via_stochastic_processes/issues/10 

There are some other issues I'm resolving through the process of reproducing this work (eg. fixing the seed for [data loading](https://pytorch.org/docs/stable/data.html#randomness-in-multi-process-data-loading)). I plan to release the correct, reproducible version of this work once I ensure that all the results can be perfectly replicated. Again, apologies for the wait!
