### ISSUE TITLE
please check it in " C.1 NORMAL TEXT GENERATION"

### ISSUE THREAD

**Issue by Hansen06** [rosewang2008/language_modeling_via_stochastic_processes#16]
We pin our trajectory to the start and end latent, and run the Brownian bridge using Equation ??

please check it,thanks

**Comment by Hansen06** [comment]
![image](https://user-images.githubusercontent.com/20606973/200254342-73835f6b-473d-4c0f-a98d-df55850f0359.png)

**Comment by rosewang2008** [comment]
Hey! Thanks for raising this to my attention. That part of the paper refers this part of the code -- discrete sampling from the Brownian bridge: https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/main/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/run_decoding_from_embeddings.py#L75-L96 

I'll make sure to update the paper to include this edit. 

FWIW, the current repository contains a lot of refactoring bugs which I've been diligently working through. I expect to release a cleaner, reproducible version in due time. Apologies for the wait!
