### ISSUE TITLE
The classification_model attribute cannot be found from the code...

### ISSUE THREAD

**Issue by wutong4012** [rosewang2008/language_modeling_via_stochastic_processes#2]
https://github.com/rosewang2008/language_modeling_via_stochastic_processes/blob/95b5492ebc0e85c719b364e604dd91936822ac51/language_modeling_via_stochastic_processes/transformers/examples/pytorch/text-generation/generation_metrics.py#L24

**Comment by rosewang2008** [comment]
Sorry, that code shouldn't be used anymore - it was an old metric. I've now removed it in this recent commit: https://github.com/rosewang2008/language_modeling_via_stochastic_processes/commit/0b2f03aaa38bb0b59d7359ac43115e18e76e264b

Thanks for pointing that out!
