### ISSUE TITLE
Question in your generation process :simulate_brownian_bridge 

### ISSUE THREAD

**Issue by liyzh28** [rosewang2008/language_modeling_via_stochastic_processes#7]
Thx for opening your source code! 
However there exists some problems:
In the run_decoding_from_embeddings.py, 
line 91: x_tp1 = x_t,
this code doesnt work,  should it be reverse?

**Comment by liyzh28** [comment]
> Thx for opening your source code! However there exists some problems: In the run_decoding_from_embeddings.py, line 91: x_tp1 = x_t, this code doesnt work, should it be reverse?

Or I may mislead by your variable name, x_t shall be B0, and this line(91) should be deleted.

**Comment by rosewang2008** [comment]
Sorry for the late response, and thank you for catching this mistake! I've just pushed a change that corrects this.

**Comment by yunzhel2** [comment]
Thanks for your reply! 

I believe it is an attractive work and want to follow it. When try to reproduce your experiments, I meet some conflicts of performance in long-text generation shown as follows(ordering task):

|             | report     | reproduce  |
| ----------- | ---------- | ---------- |
| wikisection |            |            |
| TC-8        | 52.3 ± 2.5 | 58.0 ± 2.3 |
| TC-16       | 57.9 ± 1.0 | 51.3 ± 2.4 |
| TC-32       | 36.5 ± 2.8 | 64.7 ± 2.3 |
| wikihow     |            |            |
| TC-8        | 76.7 ± 7.5 | 73.3 ± 2.8 |
| TC-16       | 63.1 ± 6.2 | 56.0 ± 3.2 |
| TC-32       | 59.1 ± 5.5 | 60.0 ± 3.1 |

Besides, TC meet completely fail in tickettalk dataset. 

I follow the instruction in your README and used the default setting. It is clear that there exists a huge gap between the results.  I hope you could show more details of your experiment setting, and whether you did the significance test.

Look forward to your early reply!

**Comment by liyzh28** [comment]
Thanks for your reply! 

I believe it is an attractive work and want to follow it. When try to reproduce your experiments, I meet some conflicts of performance in long-text generation shown as follows(ordering task):

|             | report     | reproduce  |
| ----------- | ---------- | ---------- |
| wikisection |            |            |
| TC-8        | 52.3 ± 2.5 | 58.0 ± 2.3 |
| TC-16       | 57.9 ± 1.0 | 51.3 ± 2.4 |
| TC-32       | 36.5 ± 2.8 | 64.7 ± 2.3 |
| wikihow     |            |            |
| TC-8        | 76.7 ± 7.5 | 73.3 ± 2.8 |
| TC-16       | 63.1 ± 6.2 | 56.0 ± 3.2 |
| TC-32       | 59.1 ± 5.5 | 60.0 ± 3.1 |

Besides, TC meet completely fail in tickettalk dataset. 

I follow the instruction in your README and used the default setting. It is clear that there exists a huge gap between the results.  I hope you could show more details of your experiment setting, and whether you did the significance test.

Look forward to your early reply!
